# Generated by Django 5.2.7 on 2025-11-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LabelStudioIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("api_key", models.CharField(max_length=255)),
                ("ml_backend_url", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
