# Generated by Django 5.2.7 on 2025-11-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labelstudiointegration",
            name="url",
            field=models.CharField(max_length=255),
        ),
    ]
