# Generated by Django 5.2.7 on 2025-11-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_alter_labelstudiointegration_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labelstudiointegration",
            name="ml_backend_url",
            field=models.URLField(blank=True, default="http://example.com"),
            preserve_default=False,
        ),
    ]
